import { Patient, Doctor, Appointment, MedicalRecord, Invoice } from '@/types';

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    code: 'BN001',
    fullName: 'Nguyễn Thị Lan',
    dateOfBirth: '1985-03-15',
    gender: 'Nữ',
    phone: '0912345678',
    email: 'lan.nguyen@gmail.com',
    address: '12 Lê Lợi, Quận 1, TP.HCM',
    bloodType: 'A+',
    allergies: 'Penicillin',
    chronicDiseases: 'Tăng huyết áp',
    emergencyContact: 'Nguyễn Văn Hùng',
    emergencyPhone: '0987654321',
    insuranceNumber: 'DN4012345678',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-06-15T10:30:00Z',
    notes: 'Bệnh nhân thường xuyên, cần theo dõi huyết áp định kỳ',
  },
  {
    id: 'p2',
    code: 'BN002',
    fullName: 'Trần Văn Minh',
    dateOfBirth: '1972-07-22',
    gender: 'Nam',
    phone: '0934567890',
    email: 'minh.tran@yahoo.com',
    address: '45 Nguyễn Huệ, Quận 1, TP.HCM',
    bloodType: 'O+',
    allergies: '',
    chronicDiseases: 'Tiểu đường type 2',
    emergencyContact: 'Trần Thị Hoa',
    emergencyPhone: '0923456789',
    insuranceNumber: 'DN4023456789',
    createdAt: '2024-02-05T09:00:00Z',
    updatedAt: '2024-07-20T14:00:00Z',
    notes: 'Kiểm soát đường huyết tốt, dùng metformin',
  },
  {
    id: 'p3',
    code: 'BN003',
    fullName: 'Lê Thị Hương',
    dateOfBirth: '1990-11-08',
    gender: 'Nữ',
    phone: '0956789012',
    email: 'huong.le@gmail.com',
    address: '78 Trần Hưng Đạo, Quận 5, TP.HCM',
    bloodType: 'B+',
    allergies: 'Sulfonamide',
    chronicDiseases: '',
    emergencyContact: 'Lê Văn Nam',
    emergencyPhone: '0945678901',
    createdAt: '2024-03-12T10:00:00Z',
    updatedAt: '2024-07-01T11:00:00Z',
  },
  {
    id: 'p4',
    code: 'BN004',
    fullName: 'Phạm Quốc Bảo',
    dateOfBirth: '1965-05-30',
    gender: 'Nam',
    phone: '0978901234',
    email: '',
    address: '23 Điện Biên Phủ, Quận 3, TP.HCM',
    bloodType: 'AB+',
    allergies: '',
    chronicDiseases: 'Gout, Tăng huyết áp',
    emergencyContact: 'Phạm Thị Nga',
    emergencyPhone: '0967890123',
    insuranceNumber: 'DN4034567890',
    createdAt: '2024-01-20T08:30:00Z',
    updatedAt: '2024-08-10T09:00:00Z',
    notes: 'Hạn chế ăn hải sản, nội tạng động vật',
  },
  {
    id: 'p5',
    code: 'BN005',
    fullName: 'Hoàng Thị Mai',
    dateOfBirth: '1998-02-14',
    gender: 'Nữ',
    phone: '0901234567',
    email: 'mai.hoang@gmail.com',
    address: '56 Lý Thường Kiệt, Quận 10, TP.HCM',
    bloodType: 'A-',
    allergies: 'Aspirin',
    chronicDiseases: '',
    createdAt: '2024-04-08T11:00:00Z',
    updatedAt: '2024-07-25T15:00:00Z',
  },
  {
    id: 'p6',
    code: 'BN006',
    fullName: 'Vũ Đình Thắng',
    dateOfBirth: '1980-09-18',
    gender: 'Nam',
    phone: '0923456780',
    email: 'thang.vu@gmail.com',
    address: '34 Cách Mạng Tháng 8, Quận Tân Bình, TP.HCM',
    bloodType: 'B-',
    allergies: '',
    chronicDiseases: 'Viêm khớp dạng thấp',
    emergencyContact: 'Vũ Thị Liên',
    emergencyPhone: '0912345670',
    insuranceNumber: 'DN4045678901',
    createdAt: '2024-02-28T09:30:00Z',
    updatedAt: '2024-08-05T10:00:00Z',
  },
  {
    id: 'p7',
    code: 'BN007',
    fullName: 'Đặng Thị Thúy',
    dateOfBirth: '1955-12-25',
    gender: 'Nữ',
    phone: '0945671234',
    email: '',
    address: '90 Hai Bà Trưng, Quận 1, TP.HCM',
    bloodType: 'O-',
    allergies: 'Morphine',
    chronicDiseases: 'Loãng xương, Tăng huyết áp, Tiểu đường type 2',
    emergencyContact: 'Đặng Văn Khoa',
    emergencyPhone: '0934561234',
    insuranceNumber: 'DN4056789012',
    createdAt: '2023-11-15T08:00:00Z',
    updatedAt: '2024-08-15T11:30:00Z',
    notes: 'Bệnh nhân cao tuổi, cần chú ý tương tác thuốc',
  },
  {
    id: 'p8',
    code: 'BN008',
    fullName: 'Bùi Thanh Tùng',
    dateOfBirth: '1995-06-10',
    gender: 'Nam',
    phone: '0967892345',
    email: 'tung.bui@gmail.com',
    address: '11 Nguyễn Đình Chiểu, Quận 3, TP.HCM',
    bloodType: 'A+',
    allergies: '',
    chronicDiseases: '',
    createdAt: '2024-05-20T10:00:00Z',
    updatedAt: '2024-07-30T09:00:00Z',
  },
  {
    id: 'p9',
    code: 'BN009',
    fullName: 'Ngô Thị Phương',
    dateOfBirth: '1988-04-03',
    gender: 'Nữ',
    phone: '0989013456',
    email: 'phuong.ngo@yahoo.com',
    address: '67 Phan Xích Long, Quận Phú Nhuận, TP.HCM',
    bloodType: 'AB-',
    allergies: 'Ibuprofen',
    chronicDiseases: 'Hen suyễn',
    emergencyContact: 'Ngô Văn Tuấn',
    emergencyPhone: '0978012345',
    createdAt: '2024-03-25T14:00:00Z',
    updatedAt: '2024-08-01T10:00:00Z',
    notes: 'Mang theo thuốc xịt salbutamol',
  },
  {
    id: 'p10',
    code: 'BN010',
    fullName: 'Lý Văn Đức',
    dateOfBirth: '1978-08-20',
    gender: 'Nam',
    phone: '0912340678',
    email: 'duc.ly@gmail.com',
    address: '29 Võ Thị Sáu, Quận 3, TP.HCM',
    bloodType: 'B+',
    allergies: '',
    chronicDiseases: 'Viêm loét dạ dày',
    emergencyContact: 'Lý Thị Bích',
    emergencyPhone: '0901230678',
    insuranceNumber: 'DN4067890123',
    createdAt: '2024-01-05T08:00:00Z',
    updatedAt: '2024-07-10T13:00:00Z',
  },
  {
    id: 'p11',
    code: 'BN011',
    fullName: 'Trịnh Thị Kim Anh',
    dateOfBirth: '2001-01-15',
    gender: 'Nữ',
    phone: '0934512345',
    email: 'kimanh.trinh@gmail.com',
    address: '15 Lê Văn Sỹ, Quận 3, TP.HCM',
    bloodType: 'O+',
    allergies: '',
    chronicDiseases: '',
    createdAt: '2024-06-15T09:00:00Z',
    updatedAt: '2024-08-12T10:00:00Z',
  },
  {
    id: 'p12',
    code: 'BN012',
    fullName: 'Phan Văn Khải',
    dateOfBirth: '1962-10-05',
    gender: 'Nam',
    phone: '0956701234',
    email: '',
    address: '88 Nguyễn Trãi, Quận 5, TP.HCM',
    bloodType: 'A+',
    allergies: 'Codeine',
    chronicDiseases: 'Tim mạch vành, Tăng huyết áp',
    emergencyContact: 'Phan Thị Loan',
    emergencyPhone: '0945601234',
    insuranceNumber: 'DN4078901234',
    createdAt: '2023-12-01T08:00:00Z',
    updatedAt: '2024-08-20T11:00:00Z',
    notes: 'Dùng aspirin phòng ngừa hàng ngày',
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'd1',
    code: 'BS001',
    fullName: 'TS.BS. Nguyễn Văn Hải',
    specialty: 'Nội tổng quát',
    phone: '0901111111',
    email: 'hai.nguyen@phongkham.vn',
    licenseNumber: 'GP-001234',
    education: 'Tiến sĩ Y khoa - Đại học Y Hà Nội',
    experience: 20,
    schedule: [
      { dayOfWeek: 1, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 1, startTime: '13:30', endTime: '17:00' },
      { dayOfWeek: 3, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 5, startTime: '07:30', endTime: '11:30' },
    ],
    bio: 'Chuyên gia nội khoa với 20 năm kinh nghiệm, từng công tác tại Bệnh viện Chợ Rẫy',
    status: 'active',
    consultationFee: 300000,
  },
  {
    id: 'd2',
    code: 'BS002',
    fullName: 'ThS.BS. Trần Thị Bích Ngọc',
    specialty: 'Tim mạch',
    phone: '0902222222',
    email: 'ngoc.tran@phongkham.vn',
    licenseNumber: 'GP-002345',
    education: 'Thạc sĩ Tim mạch - Đại học Y Dược TP.HCM',
    experience: 15,
    schedule: [
      { dayOfWeek: 2, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 4, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 4, startTime: '13:30', endTime: '17:00' },
      { dayOfWeek: 6, startTime: '07:30', endTime: '11:30' },
    ],
    bio: 'Chuyên gia tim mạch, chuyên điều trị tăng huyết áp và bệnh van tim',
    status: 'active',
    consultationFee: 350000,
  },
  {
    id: 'd3',
    code: 'BS003',
    fullName: 'BS.CKI. Lê Minh Tuấn',
    specialty: 'Nội tiết - Tiểu đường',
    phone: '0903333333',
    email: 'tuan.le@phongkham.vn',
    licenseNumber: 'GP-003456',
    education: 'Chuyên khoa I Nội tiết - Đại học Y Hà Nội',
    experience: 12,
    schedule: [
      { dayOfWeek: 1, startTime: '13:30', endTime: '17:00' },
      { dayOfWeek: 3, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 3, startTime: '13:30', endTime: '17:00' },
      { dayOfWeek: 5, startTime: '13:30', endTime: '17:00' },
    ],
    bio: 'Chuyên gia nội tiết, điều trị tiểu đường và rối loạn tuyến giáp',
    status: 'active',
    consultationFee: 280000,
  },
  {
    id: 'd4',
    code: 'BS004',
    fullName: 'BS.CKII. Phạm Thị Thanh Hà',
    specialty: 'Da liễu',
    phone: '0904444444',
    email: 'ha.pham@phongkham.vn',
    licenseNumber: 'GP-004567',
    education: 'Chuyên khoa II Da liễu - Đại học Y Dược TP.HCM',
    experience: 18,
    schedule: [
      { dayOfWeek: 2, startTime: '13:30', endTime: '17:00' },
      { dayOfWeek: 4, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 6, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 6, startTime: '13:30', endTime: '17:00' },
    ],
    bio: 'Chuyên gia da liễu, điều trị mụn trứng cá, viêm da, và các bệnh da mãn tính',
    status: 'active',
    consultationFee: 320000,
  },
  {
    id: 'd5',
    code: 'BS005',
    fullName: 'TS.BS. Hoàng Ngọc Sơn',
    specialty: 'Tiêu hóa',
    phone: '0905555555',
    email: 'son.hoang@phongkham.vn',
    licenseNumber: 'GP-005678',
    education: 'Tiến sĩ Tiêu hóa - Đại học Y Hà Nội',
    experience: 22,
    schedule: [
      { dayOfWeek: 1, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 2, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 5, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 5, startTime: '13:30', endTime: '17:00' },
    ],
    bio: 'Chuyên gia tiêu hóa, nội soi dạ dày và đại tràng',
    status: 'active',
    consultationFee: 350000,
  },
  {
    id: 'd6',
    code: 'BS006',
    fullName: 'ThS.BS. Võ Thị Lan Anh',
    specialty: 'Nhi khoa',
    phone: '0906666666',
    email: 'lananh.vo@phongkham.vn',
    licenseNumber: 'GP-006789',
    education: 'Thạc sĩ Nhi khoa - Đại học Y Dược TP.HCM',
    experience: 10,
    schedule: [
      { dayOfWeek: 2, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 3, startTime: '07:30', endTime: '11:30' },
      { dayOfWeek: 4, startTime: '13:30', endTime: '17:00' },
      { dayOfWeek: 6, startTime: '07:30', endTime: '11:30' },
    ],
    bio: 'Bác sĩ nhi khoa, chuyên chăm sóc sức khỏe trẻ em từ sơ sinh đến 16 tuổi',
    status: 'inactive',
    consultationFee: 250000,
  },
];

const today = new Date();
const todayStr = today.toISOString().split('T')[0];
const yesterday = new Date(today);
yesterday.setDate(today.getDate() - 1);
const yesterdayStr = yesterday.toISOString().split('T')[0];
const tomorrow = new Date(today);
tomorrow.setDate(today.getDate() + 1);
const tomorrowStr = tomorrow.toISOString().split('T')[0];
const twoDaysAgo = new Date(today);
twoDaysAgo.setDate(today.getDate() - 2);
const twoDaysAgoStr = twoDaysAgo.toISOString().split('T')[0];
const nextWeek = new Date(today);
nextWeek.setDate(today.getDate() + 7);
const nextWeekStr = nextWeek.toISOString().split('T')[0];

export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    code: 'LH001',
    patientId: 'p1',
    patientName: 'Nguyễn Thị Lan',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    date: todayStr,
    time: '08:00',
    reason: 'Kiểm tra huyết áp định kỳ',
    status: 'hoàn thành',
    room: 'Phòng 1',
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'a2',
    code: 'LH002',
    patientId: 'p2',
    patientName: 'Trần Văn Minh',
    doctorId: 'd3',
    doctorName: 'BS.CKI. Lê Minh Tuấn',
    date: todayStr,
    time: '09:00',
    reason: 'Theo dõi đường huyết',
    status: 'đang khám',
    room: 'Phòng 3',
    createdAt: '2024-08-02T08:00:00Z',
    updatedAt: '2024-08-02T08:00:00Z',
  },
  {
    id: 'a3',
    code: 'LH003',
    patientId: 'p4',
    patientName: 'Phạm Quốc Bảo',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    date: todayStr,
    time: '10:00',
    reason: 'Đau khớp, tái khám Gout',
    status: 'chờ khám',
    room: 'Phòng 1',
    createdAt: '2024-08-05T09:00:00Z',
    updatedAt: '2024-08-05T09:00:00Z',
  },
  {
    id: 'a4',
    code: 'LH004',
    patientId: 'p9',
    patientName: 'Ngô Thị Phương',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    date: todayStr,
    time: '10:30',
    reason: 'Khó thở, ho kéo dài',
    status: 'chờ khám',
    room: 'Phòng 1',
    createdAt: '2024-08-10T10:00:00Z',
    updatedAt: '2024-08-10T10:00:00Z',
  },
  {
    id: 'a5',
    code: 'LH005',
    patientId: 'p12',
    patientName: 'Phan Văn Khải',
    doctorId: 'd2',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    date: todayStr,
    time: '08:30',
    reason: 'Kiểm tra tim mạch định kỳ',
    status: 'hoàn thành',
    room: 'Phòng 2',
    createdAt: '2024-08-08T11:00:00Z',
    updatedAt: '2024-08-08T11:00:00Z',
  },
  {
    id: 'a6',
    code: 'LH006',
    patientId: 'p3',
    patientName: 'Lê Thị Hương',
    doctorId: 'd4',
    doctorName: 'BS.CKII. Phạm Thị Thanh Hà',
    date: todayStr,
    time: '14:00',
    reason: 'Nổi mẩn đỏ, ngứa da',
    status: 'chờ khám',
    room: 'Phòng 4',
    createdAt: '2024-08-12T09:00:00Z',
    updatedAt: '2024-08-12T09:00:00Z',
  },
  {
    id: 'a7',
    code: 'LH007',
    patientId: 'p5',
    patientName: 'Hoàng Thị Mai',
    doctorId: 'd4',
    doctorName: 'BS.CKII. Phạm Thị Thanh Hà',
    date: todayStr,
    time: '15:00',
    reason: 'Kiểm tra da liễu',
    status: 'chờ khám',
    room: 'Phòng 4',
    createdAt: '2024-08-13T14:00:00Z',
    updatedAt: '2024-08-13T14:00:00Z',
  },
  {
    id: 'a8',
    code: 'LH008',
    patientId: 'p7',
    patientName: 'Đặng Thị Thúy',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    date: yesterdayStr,
    time: '08:00',
    reason: 'Theo dõi huyết áp và đường huyết',
    status: 'hoàn thành',
    room: 'Phòng 1',
    notes: 'Huyết áp ổn định, đường huyết trong giới hạn',
    createdAt: '2024-08-01T08:00:00Z',
    updatedAt: '2024-08-01T08:00:00Z',
  },
  {
    id: 'a9',
    code: 'LH009',
    patientId: 'p10',
    patientName: 'Lý Văn Đức',
    doctorId: 'd5',
    doctorName: 'TS.BS. Hoàng Ngọc Sơn',
    date: yesterdayStr,
    time: '09:30',
    reason: 'Đau bụng, buồn nôn',
    status: 'hoàn thành',
    room: 'Phòng 5',
    notes: 'Viêm loét dạ dày tiến triển, cần điều trị 4 tuần',
    createdAt: '2024-08-05T10:00:00Z',
    updatedAt: '2024-08-05T10:00:00Z',
  },
  {
    id: 'a10',
    code: 'LH010',
    patientId: 'p6',
    patientName: 'Vũ Đình Thắng',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    date: yesterdayStr,
    time: '14:00',
    reason: 'Đau khớp tay, sưng buổi sáng',
    status: 'hủy',
    room: 'Phòng 1',
    notes: 'Bệnh nhân hủy hẹn vì bận',
    createdAt: '2024-08-10T09:00:00Z',
    updatedAt: '2024-08-10T09:00:00Z',
  },
  {
    id: 'a11',
    code: 'LH011',
    patientId: 'p8',
    patientName: 'Bùi Thanh Tùng',
    doctorId: 'd5',
    doctorName: 'TS.BS. Hoàng Ngọc Sơn',
    date: tomorrowStr,
    time: '08:00',
    reason: 'Nội soi dạ dày kiểm tra',
    status: 'chờ khám',
    room: 'Phòng 5',
    createdAt: '2024-08-14T11:00:00Z',
    updatedAt: '2024-08-14T11:00:00Z',
  },
  {
    id: 'a12',
    code: 'LH012',
    patientId: 'p11',
    patientName: 'Trịnh Thị Kim Anh',
    doctorId: 'd2',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    date: tomorrowStr,
    time: '09:00',
    reason: 'Tim đập nhanh, hồi hộp',
    status: 'chờ khám',
    room: 'Phòng 2',
    createdAt: '2024-08-15T10:00:00Z',
    updatedAt: '2024-08-15T10:00:00Z',
  },
  {
    id: 'a13',
    code: 'LH013',
    patientId: 'p1',
    patientName: 'Nguyễn Thị Lan',
    doctorId: 'd2',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    date: nextWeekStr,
    time: '10:00',
    reason: 'Tái khám huyết áp',
    status: 'chờ khám',
    room: 'Phòng 2',
    createdAt: '2024-08-15T09:00:00Z',
    updatedAt: '2024-08-15T09:00:00Z',
  },
  {
    id: 'a14',
    code: 'LH014',
    patientId: 'p2',
    patientName: 'Trần Văn Minh',
    doctorId: 'd3',
    doctorName: 'BS.CKI. Lê Minh Tuấn',
    date: twoDaysAgoStr,
    time: '08:30',
    reason: 'Xét nghiệm HbA1c định kỳ',
    status: 'hoàn thành',
    room: 'Phòng 3',
    createdAt: '2024-08-10T08:00:00Z',
    updatedAt: '2024-08-10T08:00:00Z',
  },
  {
    id: 'a15',
    code: 'LH015',
    patientId: 'p7',
    patientName: 'Đặng Thị Thúy',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    date: twoDaysAgoStr,
    time: '14:30',
    reason: 'Đau đầu, chóng mặt',
    status: 'hoàn thành',
    room: 'Phòng 1',
    createdAt: '2024-08-11T09:00:00Z',
    updatedAt: '2024-08-11T09:00:00Z',
  },
  {
    id: 'a16',
    code: 'LH016',
    patientId: 'p4',
    patientName: 'Phạm Quốc Bảo',
    doctorId: 'd2',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    date: nextWeekStr,
    time: '08:00',
    reason: 'Siêu âm tim',
    status: 'chờ khám',
    room: 'Phòng 2',
    createdAt: '2024-08-13T11:00:00Z',
    updatedAt: '2024-08-13T11:00:00Z',
  },
  {
    id: 'a17',
    code: 'LH017',
    patientId: 'p3',
    patientName: 'Lê Thị Hương',
    doctorId: 'd4',
    doctorName: 'BS.CKII. Phạm Thị Thanh Hà',
    date: yesterdayStr,
    time: '13:30',
    reason: 'Viêm da cơ địa',
    status: 'hoàn thành',
    room: 'Phòng 4',
    createdAt: '2024-08-10T09:00:00Z',
    updatedAt: '2024-08-10T09:00:00Z',
  },
  {
    id: 'a18',
    code: 'LH018',
    patientId: 'p10',
    patientName: 'Lý Văn Đức',
    doctorId: 'd5',
    doctorName: 'TS.BS. Hoàng Ngọc Sơn',
    date: nextWeekStr,
    time: '09:00',
    reason: 'Tái khám dạ dày',
    status: 'chờ khám',
    room: 'Phòng 5',
    createdAt: '2024-08-14T10:00:00Z',
    updatedAt: '2024-08-14T10:00:00Z',
  },
  {
    id: 'a19',
    code: 'LH019',
    patientId: 'p5',
    patientName: 'Hoàng Thị Mai',
    doctorId: 'd4',
    doctorName: 'BS.CKII. Phạm Thị Thanh Hà',
    date: twoDaysAgoStr,
    time: '15:00',
    reason: 'Mụn trứng cá nặng',
    status: 'hoàn thành',
    room: 'Phòng 4',
    createdAt: '2024-08-12T09:00:00Z',
    updatedAt: '2024-08-12T09:00:00Z',
  },
  {
    id: 'a20',
    code: 'LH020',
    patientId: 'p12',
    patientName: 'Phan Văn Khải',
    doctorId: 'd2',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    date: twoDaysAgoStr,
    time: '08:00',
    reason: 'Tức ngực, khó thở khi gắng sức',
    status: 'hoàn thành',
    room: 'Phòng 2',
    createdAt: '2024-08-12T10:00:00Z',
    updatedAt: '2024-08-12T10:00:00Z',
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'mr1',
    code: 'HS001',
    patientId: 'p1',
    patientName: 'Nguyễn Thị Lan',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    appointmentId: 'a1',
    visitDate: todayStr,
    chiefComplaint: 'Kiểm tra huyết áp định kỳ',
    diagnosis: 'Tăng huyết áp độ I, kiểm soát tốt',
    icdCode: 'I10',
    symptoms: 'Không có triệu chứng bất thường, huyết áp đo được 130/85 mmHg',
    examination: 'Huyết áp: 130/85 mmHg, Mạch: 72 lần/phút, SpO2: 98%, Nhịp tim đều',
    treatment: 'Tiếp tục thuốc amlodipine 5mg hiện tại, tái khám sau 1 tháng',
    prescriptions: [
      {
        id: 'rx1',
        medicineName: 'Amlodipine 5mg',
        dosage: '5mg',
        frequency: '1 lần/ngày',
        duration: '30 ngày',
        instructions: 'Uống vào buổi sáng sau ăn',
        quantity: 30,
        unit: 'viên',
      },
      {
        id: 'rx2',
        medicineName: 'Losartan 50mg',
        dosage: '50mg',
        frequency: '1 lần/ngày',
        duration: '30 ngày',
        instructions: 'Uống vào buổi tối sau ăn',
        quantity: 30,
        unit: 'viên',
      },
    ],
    labTests: [
      {
        id: 'lt1',
        testName: 'Huyết áp',
        result: '130/85',
        normalRange: '<130/80',
        unit: 'mmHg',
        status: 'bất thường',
      },
    ],
    followUpDate: nextWeekStr,
    notes: 'Khuyến cáo hạn chế muối, tập thể dục nhẹ 30 phút/ngày',
    createdAt: todayStr + 'T08:30:00Z',
    updatedAt: todayStr + 'T08:30:00Z',
  },
  {
    id: 'mr2',
    code: 'HS002',
    patientId: 'p2',
    patientName: 'Trần Văn Minh',
    doctorId: 'd3',
    doctorName: 'BS.CKI. Lê Minh Tuấn',
    appointmentId: 'a14',
    visitDate: twoDaysAgoStr,
    chiefComplaint: 'Xét nghiệm HbA1c định kỳ, kiểm soát đường huyết',
    diagnosis: 'Đái tháo đường type 2, kiểm soát ổn',
    icdCode: 'E11',
    symptoms: 'Đường huyết lúc đói 7.2 mmol/L, HbA1c 7.1%',
    examination: 'Đường huyết lúc đói: 7.2 mmol/L, HbA1c: 7.1%, Không có biến chứng cấp',
    treatment: 'Duy trì metformin, thêm glimepiride nếu không kiểm soát được sau 3 tháng',
    prescriptions: [
      {
        id: 'rx3',
        medicineName: 'Metformin 500mg',
        dosage: '500mg',
        frequency: '2 lần/ngày',
        duration: '90 ngày',
        instructions: 'Uống trong bữa ăn sáng và tối',
        quantity: 180,
        unit: 'viên',
      },
    ],
    labTests: [
      {
        id: 'lt2',
        testName: 'HbA1c',
        result: '7.1',
        normalRange: '<7.0',
        unit: '%',
        status: 'bất thường',
      },
      {
        id: 'lt3',
        testName: 'Đường huyết lúc đói',
        result: '7.2',
        normalRange: '3.9-6.1',
        unit: 'mmol/L',
        status: 'bất thường',
      },
    ],
    followUpDate: nextWeekStr,
    notes: 'Tư vấn chế độ ăn kiêng đường, tăng cường vận động',
    createdAt: twoDaysAgoStr + 'T09:00:00Z',
    updatedAt: twoDaysAgoStr + 'T09:00:00Z',
  },
  {
    id: 'mr3',
    code: 'HS003',
    patientId: 'p10',
    patientName: 'Lý Văn Đức',
    doctorId: 'd5',
    doctorName: 'TS.BS. Hoàng Ngọc Sơn',
    appointmentId: 'a9',
    visitDate: yesterdayStr,
    chiefComplaint: 'Đau bụng vùng thượng vị, buồn nôn sau ăn',
    diagnosis: 'Viêm loét dạ dày tá tràng tiến triển',
    icdCode: 'K27',
    symptoms: 'Đau thượng vị, buồn nôn, ợ chua, khó tiêu sau ăn 1-2 giờ',
    examination: 'Bụng mềm, ấn đau vùng thượng vị, không phản ứng thành bụng. Nội soi: loét tá tràng D1, kích thước 0.5cm',
    treatment: 'Điều trị diệt H.pylori theo phác đồ 3 thuốc trong 14 ngày, sau đó dùng PPI 4 tuần',
    prescriptions: [
      {
        id: 'rx4',
        medicineName: 'Omeprazole 20mg',
        dosage: '20mg',
        frequency: '2 lần/ngày',
        duration: '42 ngày',
        instructions: 'Uống trước ăn 30 phút',
        quantity: 84,
        unit: 'viên',
      },
      {
        id: 'rx5',
        medicineName: 'Clarithromycin 500mg',
        dosage: '500mg',
        frequency: '2 lần/ngày',
        duration: '14 ngày',
        instructions: 'Uống cùng bữa ăn',
        quantity: 28,
        unit: 'viên',
      },
      {
        id: 'rx6',
        medicineName: 'Amoxicillin 1000mg',
        dosage: '1000mg',
        frequency: '2 lần/ngày',
        duration: '14 ngày',
        instructions: 'Uống cùng bữa ăn',
        quantity: 28,
        unit: 'viên',
      },
    ],
    labTests: [
      {
        id: 'lt4',
        testName: 'Nội soi dạ dày',
        result: 'Loét tá tràng D1, 0.5cm, H.pylori (+)',
        status: 'bất thường',
      },
    ],
    followUpDate: nextWeekStr,
    notes: 'Hạn chế rượu bia, cà phê. Không dùng NSAID. Tái khám sau 4 tuần điều trị',
    createdAt: yesterdayStr + 'T10:00:00Z',
    updatedAt: yesterdayStr + 'T10:00:00Z',
  },
  {
    id: 'mr4',
    code: 'HS004',
    patientId: 'p12',
    patientName: 'Phan Văn Khải',
    doctorId: 'd2',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    appointmentId: 'a20',
    visitDate: twoDaysAgoStr,
    chiefComplaint: 'Tức ngực khi gắng sức, khó thở leo cầu thang',
    diagnosis: 'Bệnh tim thiếu máu cục bộ ổn định',
    icdCode: 'I25',
    symptoms: 'Tức ngực khi đi bộ nhanh hoặc leo cầu thang, hết sau nghỉ ngơi 5 phút',
    examination: 'HA: 145/90 mmHg, Mạch: 78 lần/phút, đều. ECG: ST chênh nhẹ ở V4-V6. Siêu âm tim: EF 55%',
    treatment: 'Tăng liều bisoprolol, thêm isosorbide dinitrate khi cần, theo dõi sát',
    prescriptions: [
      {
        id: 'rx7',
        medicineName: 'Bisoprolol 5mg',
        dosage: '5mg',
        frequency: '1 lần/ngày',
        duration: '30 ngày',
        instructions: 'Uống buổi sáng sau ăn',
        quantity: 30,
        unit: 'viên',
      },
      {
        id: 'rx8',
        medicineName: 'Aspirin 81mg',
        dosage: '81mg',
        frequency: '1 lần/ngày',
        duration: '30 ngày',
        instructions: 'Uống sau bữa ăn',
        quantity: 30,
        unit: 'viên',
      },
      {
        id: 'rx9',
        medicineName: 'Isosorbide dinitrate 5mg',
        dosage: '5mg',
        frequency: 'Khi cần (đau ngực)',
        duration: '30 ngày',
        instructions: 'Đặt dưới lưỡi khi đau ngực',
        quantity: 20,
        unit: 'viên',
      },
    ],
    labTests: [
      {
        id: 'lt5',
        testName: 'ECG',
        result: 'ST chênh nhẹ V4-V6',
        status: 'bất thường',
      },
      {
        id: 'lt6',
        testName: 'Siêu âm tim',
        result: 'EF 55%, co bóp tốt',
        normalRange: 'EF>55%',
        status: 'bình thường',
      },
    ],
    followUpDate: nextWeekStr,
    notes: 'Cần chụp mạch vành nếu triệu chứng không cải thiện',
    createdAt: twoDaysAgoStr + 'T08:30:00Z',
    updatedAt: twoDaysAgoStr + 'T08:30:00Z',
  },
  {
    id: 'mr5',
    code: 'HS005',
    patientId: 'p7',
    patientName: 'Đặng Thị Thúy',
    doctorId: 'd1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    appointmentId: 'a8',
    visitDate: yesterdayStr,
    chiefComplaint: 'Theo dõi đa bệnh lý: tăng huyết áp, tiểu đường, loãng xương',
    diagnosis: 'Tăng huyết áp độ II + Đái tháo đường type 2 + Loãng xương nặng',
    icdCode: 'I10, E11, M81',
    symptoms: 'HA 160/95 mmHg, đường huyết lúc đói 9.8 mmol/L, đau lưng kéo dài',
    examination: 'HA: 160/95 mmHg, Mạch: 80 lần/phút, Đường huyết: 9.8 mmol/L, BMD: -2.8 SD',
    treatment: 'Điều chỉnh thuốc huyết áp, thêm insulin nền, điều trị loãng xương',
    prescriptions: [
      {
        id: 'rx10',
        medicineName: 'Amlodipine 10mg',
        dosage: '10mg',
        frequency: '1 lần/ngày',
        duration: '30 ngày',
        instructions: 'Uống buổi sáng',
        quantity: 30,
        unit: 'viên',
      },
      {
        id: 'rx11',
        medicineName: 'Metformin 1000mg',
        dosage: '1000mg',
        frequency: '2 lần/ngày',
        duration: '30 ngày',
        instructions: 'Uống cùng bữa ăn',
        quantity: 60,
        unit: 'viên',
      },
      {
        id: 'rx12',
        medicineName: 'Calcium 500mg + D3',
        dosage: '500mg',
        frequency: '2 lần/ngày',
        duration: '90 ngày',
        instructions: 'Uống sau bữa ăn',
        quantity: 180,
        unit: 'viên',
      },
    ],
    followUpDate: nextWeekStr,
    notes: 'Bệnh nhân cần được theo dõi sát, hẹn tái khám 2 tuần/lần',
    createdAt: yesterdayStr + 'T08:30:00Z',
    updatedAt: yesterdayStr + 'T08:30:00Z',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    code: 'HD001',
    patientId: 'p1',
    patientName: 'Nguyễn Thị Lan',
    appointmentId: 'a1',
    medicalRecordId: 'mr1',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    invoiceDate: todayStr,
    items: [
      { id: 'ii1', description: 'Phí khám bệnh - Nội tổng quát', category: 'khám bệnh', quantity: 1, unitPrice: 300000, total: 300000 },
      { id: 'ii2', description: 'Amlodipine 5mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 2500, total: 75000 },
      { id: 'ii3', description: 'Losartan 50mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 4000, total: 120000 },
    ],
    subtotal: 495000,
    discount: 0,
    tax: 0,
    total: 495000,
    paidAmount: 495000,
    paymentStatus: 'đã thanh toán',
    paymentMethod: 'tiền mặt',
    paymentDate: todayStr,
    createdAt: todayStr + 'T09:00:00Z',
  },
  {
    id: 'inv2',
    code: 'HD002',
    patientId: 'p12',
    patientName: 'Phan Văn Khải',
    appointmentId: 'a5',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    invoiceDate: todayStr,
    items: [
      { id: 'ii4', description: 'Phí khám bệnh - Tim mạch', category: 'khám bệnh', quantity: 1, unitPrice: 350000, total: 350000 },
      { id: 'ii5', description: 'ECG (điện tâm đồ)', category: 'xét nghiệm', quantity: 1, unitPrice: 150000, total: 150000 },
      { id: 'ii6', description: 'Bisoprolol 5mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 5000, total: 150000 },
    ],
    subtotal: 650000,
    discount: 50000,
    tax: 0,
    total: 600000,
    paidAmount: 600000,
    paymentStatus: 'đã thanh toán',
    paymentMethod: 'bảo hiểm',
    paymentDate: todayStr,
    notes: 'Bảo hiểm y tế chi trả 80%',
    createdAt: todayStr + 'T09:30:00Z',
  },
  {
    id: 'inv3',
    code: 'HD003',
    patientId: 'p10',
    patientName: 'Lý Văn Đức',
    appointmentId: 'a9',
    medicalRecordId: 'mr3',
    doctorName: 'TS.BS. Hoàng Ngọc Sơn',
    invoiceDate: yesterdayStr,
    items: [
      { id: 'ii7', description: 'Phí khám bệnh - Tiêu hóa', category: 'khám bệnh', quantity: 1, unitPrice: 350000, total: 350000 },
      { id: 'ii8', description: 'Nội soi dạ dày', category: 'thủ thuật', quantity: 1, unitPrice: 800000, total: 800000 },
      { id: 'ii9', description: 'Omeprazole 20mg (84 viên)', category: 'thuốc', quantity: 84, unitPrice: 3000, total: 252000 },
      { id: 'ii10', description: 'Clarithromycin 500mg (28 viên)', category: 'thuốc', quantity: 28, unitPrice: 8000, total: 224000 },
      { id: 'ii11', description: 'Amoxicillin 1000mg (28 viên)', category: 'thuốc', quantity: 28, unitPrice: 5000, total: 140000 },
    ],
    subtotal: 1766000,
    discount: 0,
    tax: 0,
    total: 1766000,
    paidAmount: 0,
    paymentStatus: 'chưa thanh toán',
    createdAt: yesterdayStr + 'T10:30:00Z',
  },
  {
    id: 'inv4',
    code: 'HD004',
    patientId: 'p2',
    patientName: 'Trần Văn Minh',
    appointmentId: 'a14',
    medicalRecordId: 'mr2',
    doctorName: 'BS.CKI. Lê Minh Tuấn',
    invoiceDate: twoDaysAgoStr,
    items: [
      { id: 'ii12', description: 'Phí khám bệnh - Nội tiết', category: 'khám bệnh', quantity: 1, unitPrice: 280000, total: 280000 },
      { id: 'ii13', description: 'Xét nghiệm HbA1c', category: 'xét nghiệm', quantity: 1, unitPrice: 250000, total: 250000 },
      { id: 'ii14', description: 'Xét nghiệm đường huyết lúc đói', category: 'xét nghiệm', quantity: 1, unitPrice: 80000, total: 80000 },
      { id: 'ii15', description: 'Metformin 500mg (180 viên)', category: 'thuốc', quantity: 180, unitPrice: 1500, total: 270000 },
    ],
    subtotal: 880000,
    discount: 88000,
    tax: 0,
    total: 792000,
    paidAmount: 792000,
    paymentStatus: 'đã thanh toán',
    paymentMethod: 'chuyển khoản',
    paymentDate: twoDaysAgoStr,
    notes: 'Giảm giá 10% bệnh nhân thường xuyên',
    createdAt: twoDaysAgoStr + 'T09:30:00Z',
  },
  {
    id: 'inv5',
    code: 'HD005',
    patientId: 'p12',
    patientName: 'Phan Văn Khải',
    appointmentId: 'a20',
    medicalRecordId: 'mr4',
    doctorName: 'ThS.BS. Trần Thị Bích Ngọc',
    invoiceDate: twoDaysAgoStr,
    items: [
      { id: 'ii16', description: 'Phí khám bệnh - Tim mạch', category: 'khám bệnh', quantity: 1, unitPrice: 350000, total: 350000 },
      { id: 'ii17', description: 'Siêu âm tim', category: 'xét nghiệm', quantity: 1, unitPrice: 400000, total: 400000 },
      { id: 'ii18', description: 'ECG (điện tâm đồ)', category: 'xét nghiệm', quantity: 1, unitPrice: 150000, total: 150000 },
      { id: 'ii19', description: 'Bisoprolol 5mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 5000, total: 150000 },
      { id: 'ii20', description: 'Aspirin 81mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 2000, total: 60000 },
    ],
    subtotal: 1110000,
    discount: 0,
    tax: 0,
    total: 1110000,
    paidAmount: 500000,
    paymentStatus: 'một phần',
    paymentMethod: 'tiền mặt',
    paymentDate: twoDaysAgoStr,
    notes: 'Còn nợ 610,000đ',
    createdAt: twoDaysAgoStr + 'T09:00:00Z',
  },
  {
    id: 'inv6',
    code: 'HD006',
    patientId: 'p7',
    patientName: 'Đặng Thị Thúy',
    appointmentId: 'a8',
    medicalRecordId: 'mr5',
    doctorName: 'TS.BS. Nguyễn Văn Hải',
    invoiceDate: yesterdayStr,
    items: [
      { id: 'ii21', description: 'Phí khám bệnh - Nội tổng quát', category: 'khám bệnh', quantity: 1, unitPrice: 300000, total: 300000 },
      { id: 'ii22', description: 'Đo mật độ xương (BMD)', category: 'xét nghiệm', quantity: 1, unitPrice: 350000, total: 350000 },
      { id: 'ii23', description: 'Amlodipine 10mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 4000, total: 120000 },
      { id: 'ii24', description: 'Metformin 1000mg (60 viên)', category: 'thuốc', quantity: 60, unitPrice: 2500, total: 150000 },
      { id: 'ii25', description: 'Calcium 500mg + D3 (180 viên)', category: 'thuốc', quantity: 180, unitPrice: 1500, total: 270000 },
    ],
    subtotal: 1190000,
    discount: 119000,
    tax: 0,
    total: 1071000,
    paidAmount: 1071000,
    paymentStatus: 'đã thanh toán',
    paymentMethod: 'bảo hiểm',
    paymentDate: yesterdayStr,
    notes: 'Bảo hiểm y tế hỗ trợ',
    createdAt: yesterdayStr + 'T09:00:00Z',
  },
  {
    id: 'inv7',
    code: 'HD007',
    patientId: 'p5',
    patientName: 'Hoàng Thị Mai',
    appointmentId: 'a19',
    doctorName: 'BS.CKII. Phạm Thị Thanh Hà',
    invoiceDate: twoDaysAgoStr,
    items: [
      { id: 'ii26', description: 'Phí khám bệnh - Da liễu', category: 'khám bệnh', quantity: 1, unitPrice: 320000, total: 320000 },
      { id: 'ii27', description: 'Adapalene gel 0.1%', category: 'thuốc', quantity: 1, unitPrice: 180000, total: 180000 },
      { id: 'ii28', description: 'Doxycycline 100mg (30 viên)', category: 'thuốc', quantity: 30, unitPrice: 4000, total: 120000 },
    ],
    subtotal: 620000,
    discount: 0,
    tax: 0,
    total: 620000,
    paidAmount: 620000,
    paymentStatus: 'đã thanh toán',
    paymentMethod: 'tiền mặt',
    paymentDate: twoDaysAgoStr,
    createdAt: twoDaysAgoStr + 'T15:30:00Z',
  },
  {
    id: 'inv8',
    code: 'HD008',
    patientId: 'p3',
    patientName: 'Lê Thị Hương',
    appointmentId: 'a17',
    doctorName: 'BS.CKII. Phạm Thị Thanh Hà',
    invoiceDate: yesterdayStr,
    items: [
      { id: 'ii29', description: 'Phí khám bệnh - Da liễu', category: 'khám bệnh', quantity: 1, unitPrice: 320000, total: 320000 },
      { id: 'ii30', description: 'Hydrocortisone cream 1%', category: 'thuốc', quantity: 2, unitPrice: 85000, total: 170000 },
      { id: 'ii31', description: 'Cetirizine 10mg (14 viên)', category: 'thuốc', quantity: 14, unitPrice: 3000, total: 42000 },
    ],
    subtotal: 532000,
    discount: 0,
    tax: 0,
    total: 532000,
    paidAmount: 0,
    paymentStatus: 'chưa thanh toán',
    createdAt: yesterdayStr + 'T14:00:00Z',
  },
];
